kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-alertmanager-config
  namespace: configure-alertmanager-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "get"
  - "list"
  resourceNames:
  - alertmanager-main
